opam-version: "2.0"
name: "down"
synopsis: "An OCaml toplevel (REPL) upgrade"
description: """\
Down is an unintrusive user experience upgrade for the `ocaml`
toplevel (REPL). 

Simply load the zero dependency `Down` library in the `ocaml` toplevel
and you get line edition, history, session support and identifier
completion and documentation (courtesy of [`ocp-index`][ocp-index]).

Add this to your `~/.ocamlinit`:

    #use "down.top"

![tty](doc/tty.png)

Down is distributed under the ISC license.

Homepage: http://erratique.ch/software/down

[ocp-index]: https://github.com/OCamlPro/ocp-index"""
maintainer: "Daniel Bünzli <daniel.buenzl i@erratique.ch>"
authors: "The down programmers"
license: "ISC"
tags: ["dev" "toplevel" "repl" "org:erratique"]
homepage: "https://erratique.ch/software/down"
doc: "https://erratique.ch/software/down/doc/"
bug-reports: "https://github.com/dbuenzli/down/issues"
depends: [
  "ocaml" {>= "4.14.0"}
  "dune" {>= "3.12"}
]
build: [[ "dune" "build" "-p" name ]]
dev-repo: "git+https://github.com/jonahbeckford/down.git"
